# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
    # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
    # http:
    #   base_url: example.duckdns.org:8123

    # Text to speech
    tts:
        - platform: google_translate

    mqtt:
        broker: 127.0.0.1
        discovery: true
        discovery_prefix: csro

    xiaomi_aqara:
        discovery_retry: 5
        gateways:
            - key: m3bjq7ol99e18xhh

    discovery:

    yeelight:
        devices:
            192.168.2.49:
                name: 卧室台灯
                model: lamp1

            192.168.2.29:
                name: 调光灯带
                model: lamp1

    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    input_boolean:
        chromecast_radio:
            name: Chromecast Radio
